### ISSUE TITLE
Can memory be smaller than disk size?

### ISSUE THREAD

**Issue by hiqsociety** [timtadh/fs2#10]
1. Can memory be smaller than disk size? what happens when it does?
2. do you have an option where the fsync is immediate?

**Comment by timtadh** [comment]
> Can memory be smaller than disk size? what happens when it does?

That is the point of an external structure. Linux (this repository was only tested on linux and explicitly does not support darwin or windows) handles paging the the blocks in and out of memory.

> do you have an option where the fsync is immediate?

No, you can always call sync yourself after a write https://github.com/timtadh/fs2/blob/master/fmap/fmap.go#L598
