### ISSUE TITLE
if i want to access a key from a file, does it read the whole file into mem or just that particular key section? just wondering if i need to have lots of mem available for this. 100GB per file size advisable etc?

### ISSUE THREAD

**Issue by hiqsociety** [timtadh/fs2#15]
if i want to access a key from a file, does it read the whole file into mem or just that particular key section? just wondering if i need to have lots of mem available for this. 100GB per file size advisable etc?

does it reclaim disk space with deleting keys since this is btree

**Comment by timtadh** [comment]
It uses memory mapped files so your file can exceed the size of you ram. The OS will transparently page the parts you are using in and out.

Note: I make *no guarantees* on the correctness of this repository. That is in the license but I wanted to highlight that here.
