### ISSUE TITLE
The 'count' of idxBlk is too small!

### ISSUE THREAD

**Issue by linkerlin** [timtadh/fs2#5]
type idxBlk struct {
	flags consts.Flag
	count uint16
	items [itemsPerIdx]uint64
}

uint32 is better.

**Comment by timtadh** [comment]
@linkerlin have you encountered an actual issue with this? It is a unit16 because its maximum values should be `itemsPerIdx` which is:

```go
const itemsPerIdx = (consts.BLOCKSIZE / 8) - 1

type idxBlk struct {
	flags consts.Flag
	count uint16
	items [itemsPerIdx]uint64
}
```

which by my math is 511.

**Comment by timtadh** [comment]
closing.
